// <auto-generated />
using System;
using EksiSozlukEntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EksiSozlukEntityFramework.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20220106192346_InitialDBDüzenleme2")]
    partial class InitialDBDüzenleme2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EksiSozlukEntityFramework.Kategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KategoriAdi");

                    b.HasKey("ID");

                    b.ToTable("Kategori");
                });

            modelBuilder.Entity("EksiSozlukEntityFramework.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Kullanıcı Adı");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Şifre");

                    b.HasKey("ID");

                    b.ToTable("Kullanıcılar");
                });

            modelBuilder.Entity("EksiSozlukEntityFramework.İcerik", b =>
                {
                    b.Property<int>("İcerikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KatID")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("Yorum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YorumTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("İcerikID");

                    b.HasIndex("KatID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("İçerik");
                });

            modelBuilder.Entity("EksiSozlukEntityFramework.İcerik", b =>
                {
                    b.HasOne("EksiSozlukEntityFramework.Kategori", "Kategori")
                        .WithMany("İcerikler")
                        .HasForeignKey("KatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EksiSozlukEntityFramework.Users", "Users")
                        .WithMany("İceriks")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EksiSozlukEntityFramework.Kategori", b =>
                {
                    b.Navigation("İcerikler");
                });

            modelBuilder.Entity("EksiSozlukEntityFramework.Users", b =>
                {
                    b.Navigation("İceriks");
                });
#pragma warning restore 612, 618
        }
    }
}
